name: React Action Workflow #workflow name

on: push # trigger

jobs:
  test: # job
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from repository
        id: get-code
        uses: actions/checkout@v4
      - name: Install Nodejs
        id: install-nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependancies
        run: npm ci
      - name: Run Tests
        run: npm test
