name: ENV Variables

on: push

# setting environment variable
env:
  WF_ENV: Available to all jobs # global env

jobs:
  log-env-job:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available to all steps in log-env job
    steps:
      - name: Log ENV Variables
        env:
          STEP_ENV: Available to only this step #available to the job only
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV ${STEP_ENV}"
      - name: Log ENV 2
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
  log_default_github_env:
    runs-on: ubuntu-latest
    steps:
      - name: Log Github ENVs
        run: |
          echo "HOME ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITUB_ACTION ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA ${GITHUB_SHA}"
          echo "GITHUB_REF ${GITHUB_REF}"
          echo "WF_ENV ${WF_ENV}"
          echo "JOB_ENV ${JOB_ENV}"    # will not be visible
          echo "STEP_ENV ${STEP_ENV}"  # will not be available

  log_test_env_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo my name
        run: echo "How di there, "

  decrypt-secret-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decript File
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secret.json --my_secret.json.gpg
        env:
          PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      - name: Print File Content
        run: cat $HOME/secret.json
