name: Github Action Functions
on: [push, pull_request]

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: |
          echo ${{ contains('hello','ll') }}
          echo ${{ startsWith('hello','he') }}
          echo ${{ endsWith('hello','l0') }}
          echo ${{ format('hello {0} {1} {3}','World','!','!') }}
  one:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    # this job will only run on push not pull_request
    # if can also be used in steps not only in jobs
    steps:
      - name: Dumpt Github context
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: eccho "$GITHUB_CONTEXT" # This step will fail because of the eccho type. You can make other steps to run even if one fails by using conditions
      - name: Dump job context
        if: failure()
        # failure() will return true, always(), cancel(), success()
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump Runner context
        if: always()
        # will always run
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
