name: Label Issues (Script Injection Examples)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Label
        env:
          TITLE: ${{github.event.issue.title}}
        run: |
          issue_title="${{ github.event.issue.title }}" 
          ```# susceptible to attacks. use environment variables```
          if [["$TITLE" == *"bug"*]]; then
          echo "Issue is about bug!"
          else
          echo "Issue is not about bug"
          fi
